swagger: "2.0"
info:
  description: Anime Recommendation System.
  version: "1.0.0"
  title: REST API for Recommending Animes to Users.
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /anime_homepage:
    get:
      operationId: Anime.homePage
      tags:
        - Anime
      summary: List of Random Animes
      description: List of Random Animes from the Dataset to Display on HomePage
      responses:
        200:
          description: SUCCESS.
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                synopsis:
                  type: string
                genre:
                  type: string
                img_url:
                  type: string

    post:
      operationId: Anime.addCount
      tags:
        - Anime
      summary: Add View Count to Anime
      description: Increase the view count of anime each time it is searched.
      parameters:
        - name: anime_name
          in: body
          description: Anime Ratings either 1 or 0
          required: True
          schema:
            type: object
            properties:
              anime_name:
                type: string
                description: Name of the seached Anime
      responses:
        201:
          description: Successfully Added View Count.

  /anime:
    get:
      operationId: Anime.returnRecommended
      tags:
        - Anime
      summary: Recommendation System for recommending anime to Users which are similar to the given Anime based on the Synopsis, Genre & Ratings.
      description: Recommend Anime based on Synopsis, Genre & Rating
      parameters:
        - name: anime_name
          in: query
          type: string
          description: Name of the Anime for the system to recommend similar Anime.
          required: true
      responses:
        200:
          description: SUCCESS.
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                synopsis:
                  type: string
                genre:
                  type: string
                img_url:
                  type: string
        404:
          description: Anime Not Found

  /anime/{genre}:
    get:
      operationId: Anime.readGenre
      tags:
        - Anime
      summary: Animes grouped by Genre
      description: GET all the anime tht belong to the given Genre.
      parameters:
        - name: genre
          in: path
          description: Genre to get the list of animes.
          type: string
          required: True
      responses:
        200:
          description: SUCCESS.
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                synopsis:
                  type: string
                genre:
                  type: string
                img_url:
                  type: string
